'''
./scripts/run_open_coding.py
'''
import os
import json
import argparse
import time
from typing import Dict, Any, Callable, Optional, List, Union
from tqdm import tqdm
import sys
from typing import Tuple
from pathlib import Path
# Ensure project root is in path
current_file_path = Path(__file__).resolve()
current_file_name = Path(__file__).stem
project_root = current_file_path.parents[2]
sys.path.append(str(project_root))
from medagentaudit.utils.logger import DualLogger
from medagentaudit.utils.encode_image import encode_image
from medagentaudit.utils.json_utils import load_jsonl, save_jsonl, preprocess_response_string
from medagentaudit.core.base_agent import BaseAgent
from medagentaudit.common.agent_type import AgentType
from medagentaudit.utils.parse_structured_output import parse_structured_output
# TODO  同样保存为jsonl，且要注意错误的日志单独输出不写入正确jsonl里。
class OpenCoder(BaseAgent):
    """
    open-coding automated open-coder for constructing full version taxonomy!
    """
    def __init__(self, model_key: str, max_retries: int = 3, retry_delay: int = 5, config_path: str = "config.toml"):
        """
        Args:
            model_key: The model key from LLM_MODELS_SETTINGS.
            max_retries: Maximum number of retries for API call failures.
            retry_delay: Delay time (in seconds) between each retry.
            config_path: Path to the configuration file.
        """
        super().__init__(agent_id="open_coder", agent_type=AgentType.OPENCODER, config_path=config_path, model_key=model_key)
        print(f"Initializing open-coder agent, ID: open_coder, Model: {model_key}")

    def annotate(self, system_message: str, user_message: Union[str, List[Dict[str, Any]]], qid: str) -> Optional[Dict[str, Any]]:
        """
        Annotate a single case log using the LLM.
        """
        user_message["content"] = [item for item in user_message["content"] if item.get("type") != "image_url"]
        retries = 0
        annotation_log = {
            "qid": qid,
            "model_name": self.model_name,
            "request": {
                "system": system_message,
                "user": user_message
            }
        }

        while retries < self.max_retries:
            try:
                response_content, reasoning_content, _, _ = self.call_llm(system_message = system_message, 
                                                                                       user_message = user_message, 
                                                                                       response_format={"type": "json_object"})
                print(f"Raw response for qid {qid}: {repr(response_content[:100])}")
                if not response_content or response_content.strip() == "":
                    raise ValueError("Empty response from API")
                
                result = json.loads(preprocess_response_string(response_content))

                if result is None:
                    raise ValueError("Could not extract valid JSON from response")
                annotation_log["parsed_output"] = result
                annotation_log["reasoning_content"] = reasoning_content
                return annotation_log

            except Exception as e:
                retries += 1
                error_message = f"LLM API call error for qid {qid} (attempt {retries}/{self.max_retries}): {e}"
                print(error_message)
                annotation_log["error"] = error_message
                if retries >= self.max_retries:
                    annotation_log["error"] = str(e)
                    print(f"LLM API call failed for qid {qid} after all retries.")
                    return annotation_log
                return annotation_log

def load_text_file(file_path: str) -> str:
    """从文件加载纯文本内容"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Critical Error: Required file not found at {file_path}")
        exit()


def parse_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    parse log files generated by different multi-agent frameworks.
    """
    try:
        qid = log_data['qid']
        ground_truth = log_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "ColaCare",
            "qid": qid,
            "question": log_data['question'],
            "options": log_data.get('options'),
            "image_path": log_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data
        }
    except KeyError as e:
        print(f"Skipping log for ColaCare due to missing key: {e}")
        return None

def parse_mdagents_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """解析由 MDAgents 框架生成的日志文件。"""
    try:
        qid = log_data['qid']
        ground_truth = log_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "MDAgents",
            "qid": qid,
            "question": log_data['question'],
            "options": log_data.get('options'),
            "image_path": log_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data.get('process_log', log_data) # 核心日志在 process_log 中
        }
    except KeyError as e:
        print(f"Skipping log for MDAgents due to missing key: {e}")
        return None

def parse_medagent_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """解析由 MedAgent 框架生成的日志文件。"""
    try:
        qid = log_data['qid']
        # 信息嵌套在 input_data 字段中
        input_data = log_data.get('input_data', {})
        ground_truth = input_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "MedAgent",
            "qid": qid,
            "question": input_data.get('question'),
            "options": input_data.get('options'),
            "image_path": input_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data.get('full_consultation_log', log_data) # 核心日志在 full_consultation_log 中
        }
    except KeyError as e:
        print(f"Skipping log for MedAgent due to missing key: {e}")
        return None

def parse_reconcile_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """解析由 ReConcile 框架生成的日志文件。"""
    try:
        qid = log_data['qid']
        ground_truth = log_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "ReConcile",
            "qid": qid,
            "question": log_data['question'],
            "options": log_data.get('options'),
            "image_path": log_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data.get('case_history', {}).get('discussion_history', log_data) # 核心日志在 case_history -> discussion_history
        }
    except KeyError as e:
        print(f"Skipping log for ReConcile due to missing key: {e}")
        return None

def get_framework_parser(framework_name: str) -> Optional[Callable[[Dict[str, Any]], Optional[Dict[str, Any]]]]:
    """根据框架名称返回相应的解析器函数。"""
    parsers = {
        "ColaCare": parse_colacare_log,
        "MDAgents": parse_mdagents_log,
        "MedAgent": parse_medagent_log,  
        "ReConcile": parse_reconcile_log
    }
    return parsers.get(framework_name)


def build_open_coding_prompts(item: Dict[str, Any], mas: str) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """
    construct the prompt basing on the characteristics of different multi-agent frameworks, return system message and user message respectively.
    """
    system_message = (f"You are a distinguished expert in medical artificial intelligence, "
                      f"possessing profound domain expertise in both clinical medicine and the architecture of medical multi-agent systems.")

    if mas.lower() == 'colacare':
        mas_description = (f"ColaCare employs a static role assignment strategy initialized before collaboration begins. The workflow follows a sequential structure: "
                           f"Initial Analysis: Assigned Doctor Agents independently provide their initial medical opinions based on the case. "
                           f"Synthesis: A Meta Agent aggregates these disparate opinions to formulate a preliminary conclusion. "
                           f"Peer Review: Doctor Agents review this preliminary conclusion, indicating their position (Agree/Disagree) and providing the rationale for their judgment. "
                           f"Decision Making: The Decision-Maker analyzes the full context of the reviews to determine the final conclusion. "
                           f"The system outputs a final answer only when a unanimous consensus is reached among all reviewers or when the maximum number of discussion rounds is exhausted.")
    elif mas.lower() == 'mac':
        mas_description = (f"The MAC system operates without specific role assignments (e.g., cardiologist, neurologist); instead, all participating agents are prompted to act as undifferentiated, general medical experts. "
                           f"The collaborative workflow follows an iterative consensus mechanism: "
                           f"1. Initial Analysis: In each round, multiple doctor agents first independently provide their initial analysis and reasoning regarding the case. "
                           f"2. Supervisor Evaluation: A Supervisor agent synthesizes these inputs to evaluate whether a consensus has been reached among the doctor agents. "
                           f"3. Decision or Iteration: "
                           f"- If the Supervisor determines that a consensus exists, it outputs the final answer and concludes the session. "
                           f"- If no consensus is found, the Supervisor triggers a new round of discussion for further deliberation.")
    elif mas.lower() == 'healthcareagent':
        mas_description = (f"The HealthcareAgent framework operates through a structured \"Plan-Analyze-Review-Decide\" workflow designed to ensure safety and accuracy in clinical reasoning: "
                           f"-Planning & Inquiry: The system first evaluates the clarity of the medical problem. "
                           f"If the query is deemed ambiguous, it initiates an inquiry process, generating three relevant follow-up questions to enrich the context before proceeding. "
                           f"-Initial Analysis: A domain agent performs the preliminary medical analysis and diagnostic reasoning based on the (potentially enriched) context. "
                           f"-Safety & Ethics Review: The initial analysis undergoes a rigorous review by specialized Safety & Ethics Reviewers. "
                           f"This stage includes specific checks for Medical Ethics, Medical Risks, and Medical Errors. "
                           f"-Decision Making: Finally, a Decision-maker aggregates the initial analysis along with the feedback from all safety reviewers to formulate the final clinical decision.")
    elif mas.lower() == 'mdagents':
        mas_description = (f"MDAgents utilizes an adaptive framework that first assesses the complexity of the medical query (Basic, Intermediate, or Advanced) to determine the collaboration structure. "
                           f"1. Intermediate Complexity: "
                            f"-Recruitment:** The system dynamically recruits a panel of experts (default: 5) tailored to the specific medical query. "
                            f"-Process: These experts conduct an independent Initial Analysis. Their findings are then aggregated and finalized by a Decision-Maker agent. "
                            f"2. Advanced Complexity: "
                            f"-Recruitment: The system recruits multiple specialized groups (default: 3 groups, including an Initial Assessment Team and a Final Review and Decision Team [FDT], totaling 9 experts. "
                            f"-Hierarchy: Each group operates under a Team Leader. "
                            f"-Process: The IDT reports first, followed by intermediate groups, and finally the FDT. "
                            f"The workflow culminates in a report generated by the team leaders, which is then used by Decision-Maker to render the final diagnosis.")
    elif mas.lower() == 'medagent':
        mas_description = """It simulates a structured consultation process. An 'Expert Gatherer' agent first identifies relevant medical specialties for the query. Then, 'Doctor' agents representing these specialties provide independent analyses. A 'Meta' (Coordinator) agent synthesizes these opinions into a single report. This report is then reviewed by the original 'Doctor' agents for agreement. Finally, a 'Decision Maker' agent produces the final answer based on the synthesis and reviews. It's a sequential process of recruitment, analysis, synthesis, review, and final decision."""
    elif mas.lower() == 'reconcile':
        mas_description = """This framework focuses on achieving consensus through debate and confidence scoring. Multiple agents generate an initial response containing 'reasoning', an 'answer', and a numerical 'confidence' score. They then engage in multiple rounds of discussion, where they are shown the grouped answers and reasonings from the previous round. After the debate rounds, a final decision is reached via a confidence-weighted vote, where responses from more confident agents are given more weight. The core mechanism is iterative refinement through debate coupled with a quantitative confidence metric."""
    system_message = f"""
    You are a meticulous AI Collaboration Analyst specialized in auditing medical multi-agent systems. 
    
    The multi-agent framework being analyzed is **{case_details['framework_name']}**.
    Framework Intent: {mas_description}
    
    Your expertise includes analyzing collaboration patterns, identifying decision-making flaws, and classifying system behaviors according to established taxonomies.
    """

    # 2. 构建用户消息 (User Message) - 具体的案例数据
    user_text_prompt = f"""
    ### TASK ###
    Audit the collaboration log of this medical multi-agent system case. Analyze the entire decision-making process, identify key success or failure patterns, and provide a structured JSON classification.

    ### TAXONOMY (Classification System) ###
    You MUST classify the case into one or more categories from the following taxonomy. Distinguish between **Failure Modes** and **Success Patterns**.

    --- TAXONOMY START ---
    {taxonomy_text}
    --- TAXONOMY END ---

    ### ANALYSIS STEPS ###
    Perform a step-by-step analysis:

    1. **Initial Assessment:** Compare initial opinions and reasoning from the first round of interactions. Are they unanimous, complementary, or contradictory?
    2. **Interaction Dynamics Analysis:** Analyze how opinions evolve, the quality of any synthesis or debate, and how disagreements are handled. Does the process lead to convergence, or do agents talk past each other?
    3. **Final Decision Analysis:** Examine how the final decision was reached. Was it based on consensus, majority vote, a weighted mechanism, or a final arbiter? Was any critical information lost?
    4. **Classification:** Select the most prominent failure or success pattern as the `primary_classification`. List any other significant patterns in `secondary_classifications`. Provide specific evidence from the log.

    ### CASE INFORMATION ###
    - **QID**: {case_details['qid']}
    - **Question**: "{case_details['question']}"
    - **Options**: {json.dumps(case_details.get('options'), indent=2)}
    - **Ground Truth Answer**: "{case_details['ground_truth']}"
    - **Final Predicted Answer**: "{case_details['predicted_answer']}"
    - **Is Final Answer Correct?**: {case_details['is_correct']}
    """
    if case_details.get('image_path'):
        user_text_prompt += f"- **Image Provided**: Yes (see below)\n"

    user_text_prompt += f"""
    
    ### INPUT LOG ###
    Here is the complete collaboration log in JSON format. Analyze the interactions:

    ```json
    {json.dumps(case_details['log_content'], indent=2, ensure_ascii=False)}
    ```

    ### OUTPUT FORMAT ###
    First, think through the analysis steps I provided internally.
    After you have completed your analysis, your final output MUST BE a single, valid JSON object. Do not include any text, explanations, or markdown formatting before or after the JSON object. The JSON should strictly adhere to the following structure:

    ```json
    {{
    "qid": "{case_details['qid']}",
    "is_correct": {str(case_details['is_correct']).lower()},
    "primary_classification": {{
        "code": "string",
        "name": "string",
        "phase": "string"
    }},
    "secondary_classifications": [
        {{
        "code": "string",
        "name": "string",
        "phase": "string"
        }}
    ],
    "evidence": "string",
    "key_moment": "string"
    }}
    ```
    """
    # 检查是否有图片需要处理
    image_path = case_details.get("image_path")
    if image_path and os.path.exists(image_path):
        base64_image = encode_image(image_path)
        print(f"Encoded image for qid {case_details['qid']}: {image_path}")
        user_content = [
            {"type": "text", "text": user_text_prompt.strip()},
            {
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"},
            },
        ]
    else:
        if image_path:
             print(f"Warning: Image path does not exist for qid {case_details['qid']}: {image_path}")
        user_content = user_text_prompt.strip()
        
    return system_message.strip(), user_content


# --- 5. MAIN EXECUTION LOGIC ---

def open_coding(item: Dict[str, Any], model_key: str, config_path: str, mas: str) -> Optional[Dict[str, Any]]:
    # prepare the system message and user message for open-coding
    system_message, user_message = build_open_coding_prompts(item=item, mas = mas)
def main():
    parser = argparse.ArgumentParser(
        description="Automate the annotation of multi-agent collaboration logs using a taxonomy.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("--model", required=True,type=str, help="The LLM model to use for open-coding,the available models are: gpt-5.2, gemini-3-flash-preview")
    parser.add_argument("--mas", required=True,type=str, help="The multiagent system to process.")
    parser.add_argument("--mas_collab_llm", required=True,type=str, help="The main llm used in the multi-agent collaboration process")
    parser.add_argument("--dataset", required=True,type=str, help="The dataset to process.")
    parser.add_argument("--config_path", type=str, required=True,help="Path to the config.toml file,default = utils/config.toml")
    args = parser.parse_args()

    mas = args.mas
    dataset = args.dataset
    mas_collab_llm = args.mas_collab_llm
    current_file_path = Path(__file__).resolve()
    project_root = current_file_path.parents[2]
    
    # adding logs
    terminal_log_file = project_root / "logs" / f"open_coding_results" / f"{mas}_{dataset}_{mas_collab_llm}_terminal.log"
    terminal_log_file.parent.mkdir(parents=True, exist_ok=True)
    print(f"!!! Terminal output is being captured to: {terminal_log_file} !!!")
    sys.stdout = DualLogger(terminal_log_file, sys.stdout)
    sys.stderr = DualLogger(terminal_log_file, sys.stderr)

    output_file = project_root / "logs" / f"open_coding_results" / f"{mas}_{dataset}_{mas_collab_llm}.jsonl"
    error_output_file = project_root / "logs" / f"open_coding_results" / f"{mas}_{dataset}_{mas_collab_llm}_errors.jsonl"
    output_file.parent.mkdir(parents=True, exist_ok=True)
    error_output_file.parent.mkdir(parents=True, exist_ok=True)

    existing_qids = set()
    if output_file.exists():
        print(f"Output file {output_file} already exists. Appending new results.")
        with open(output_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line: continue
                try:
                    record = json.loads(line)
                    if "qid" in record:
                        existing_qids.add(record["qid"])
                except json.JSONDecodeError:
                    print("Warning: Found a corrupted line in jsonl file, skipping.")
        print(f"Found {len(existing_qids)} already processed cases. They will be skipped.")

    # in this file, every mas running case is one line, and each file. has 20 cases, namely 20 lines per file.
    collaboration_file_for_opencoding = project_root / "logs" / "extracted_logs_for_open_coding" / f"{mas}_{dataset}_{mas_collab_llm}_open_coding.jsonl"
    data = load_jsonl(collaboration_file_for_opencoding)
    print(f"Total cases to process: {len(data)}")

    # --- Processing Loop ---
    print(f"\n{'='*20} Processing MAS: {mas} , dataset: {dataset}, mas_collab_llm : {mas_collab_llm} {'='*20}")
    
    for item in tqdm(data, desc=f"Running open-coding on {dataset}-{mas}-{mas_collab_llm}"): 
        qid = item["qid"]
        if qid in existing_qids:
            print(f"Skipping {qid} - already processed")
            continue

        try: 
            open_coding_result = open_coding(item = item, model_key=args.model, config_path=args.config_path, mas = mas)

            item_result = {
                "qid": qid,
                "timestamp": int(time.time()),
                "question": item["question"],
                "options": item.get("options"),
                "image_path": item.get("image_path"),
                "ground_truth": item.get("answer"),
                "predicted_answer": predicted_answer,
                "case_history": full_case_history, # This now contains the full, detailed log
            }

            save_jsonl(item_result, str(output_file))
            existing_qids.add(qid)

        except Exception as e:
            print(f"Error processing item {qid}: {e}")
            # Optionally, save an error log
            error_log = {
                "qid": qid,
                "error": str(e)
            }
            save_jsonl(error_log, str(error_output_file))

if __name__ == "__main__":
    main()