'''
./medagentaudit/annotator/open_coding_annotation.py
'''
import os
import json
import argparse
import time
from typing import Dict, Any, Callable, Optional, List, Union
from tqdm import tqdm
from openai import OpenAI
import sys
from typing import Tuple
from pathlib import Path
# Ensure project root is in path
current_file_path = Path(__file__).resolve()
current_file_name = Path(__file__).stem
utils_root = current_file_path.parents[1] / "utils"
auditor_root = current_file_path.parents[1] / "auditor"
common_root = current_file_path.parents[1] / "common"
core_root = current_file_path.parents[1] / "core"
project_root = current_file_path.parents[2]
sys.path.extend([str(utils_root), str(project_root), str(auditor_root), str(common_root)])
from logger import DualLogger
from encode_image import encode_image
from json_utils import load_jsonl, save_jsonl, preprocess_response_string
from auditor_agent import AuditorAgent
from base_agent import BaseAgent
from agent_type import AgentType
from medical_specialty import MedicalSpecialty
from parse_structured_output import parse_structured_output
# TODO  同样保存为jsonl，且要注意错误的日志单独输出不写入正确jsonl里。
class LLMAnnotator(BaseAgent):
    """
    open-coding automated annotator for constructing full version taxonomy!
    """
    def __init__(self, model_key: str, max_retries: int = 3, retry_delay: int = 5, config_path: str = "config.toml"):
        """
        Args:
            model_key: The model key from LLM_MODELS_SETTINGS.
            max_retries: Maximum number of retries for API call failures.
            retry_delay: Delay time (in seconds) between each retry.
            config_path: Path to the configuration file.
        """
        super().__init__(agent_id="annotator", agent_type=AgentType.ANNOTATOR, config_path=config_path, model_key=model_key)
        print(f"Initializing annotator agent, ID: annotator, Model: {model_key}")

    def annotate(self, system_message: str, user_message: Union[str, List[Dict[str, Any]]], qid: str) -> Optional[Dict[str, Any]]:
        """
        Annotate a single case log using the LLM.
        """
        user_message["content"] = [item for item in user_message["content"] if item.get("type") != "image_url"]
        retries = 0
        annotation_log = {
            "qid": qid,
            "model_name": self.model_name,
            "request": {
                "system": system_message,
                "user": user_message
            }
        }

        while retries < self.max_retries:
            try:
                response_content, reasoning_content, _, _ = self.call_llm(system_message = system_message, 
                                                                                       user_message = user_message, 
                                                                                       response_format={"type": "json_object"})
                print(f"Raw response for qid {qid}: {repr(response_content[:100])}")
                if not response_content or response_content.strip() == "":
                    raise ValueError("Empty response from API")
                
                result = json.loads(preprocess_response_string(response_content))

                if result is None:
                    raise ValueError("Could not extract valid JSON from response")
                annotation_log["parsed_output"] = result
                annotation_log["reasoning_content"] = reasoning_content
                return annotation_log

            except Exception as e:
                retries += 1
                error_message = f"LLM API call error for qid {qid} (attempt {retries}/{self.max_retries}): {e}"
                print(error_message)
                annotation_log["error"] = error_message
                if retries >= self.max_retries:
                    annotation_log["error"] = str(e)
                    print(f"LLM API call failed for qid {qid} after all retries.")
                    return annotation_log
                return annotation_log

def load_text_file(file_path: str) -> str:
    """从文件加载纯文本内容"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Critical Error: Required file not found at {file_path}")
        exit()


def parse_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    parse log files generated by different multi-agent frameworks.
    """
    try:
        qid = log_data['qid']
        ground_truth = log_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "ColaCare",
            "qid": qid,
            "question": log_data['question'],
            "options": log_data.get('options'),
            "image_path": log_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data
        }
    except KeyError as e:
        print(f"Skipping log for ColaCare due to missing key: {e}")
        return None

def parse_mdagents_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """解析由 MDAgents 框架生成的日志文件。"""
    try:
        qid = log_data['qid']
        ground_truth = log_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "MDAgents",
            "qid": qid,
            "question": log_data['question'],
            "options": log_data.get('options'),
            "image_path": log_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data.get('process_log', log_data) # 核心日志在 process_log 中
        }
    except KeyError as e:
        print(f"Skipping log for MDAgents due to missing key: {e}")
        return None

def parse_medagent_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """解析由 MedAgent 框架生成的日志文件。"""
    try:
        qid = log_data['qid']
        # 信息嵌套在 input_data 字段中
        input_data = log_data.get('input_data', {})
        ground_truth = input_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "MedAgent",
            "qid": qid,
            "question": input_data.get('question'),
            "options": input_data.get('options'),
            "image_path": input_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data.get('full_consultation_log', log_data) # 核心日志在 full_consultation_log 中
        }
    except KeyError as e:
        print(f"Skipping log for MedAgent due to missing key: {e}")
        return None

def parse_reconcile_log(log_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """解析由 ReConcile 框架生成的日志文件。"""
    try:
        qid = log_data['qid']
        ground_truth = log_data.get('ground_truth')
        predicted_answer = log_data.get('predicted_answer')
        gt_str = str(ground_truth).strip() if ground_truth is not None else ""
        pred_str = str(predicted_answer).strip() if predicted_answer is not None else ""
        return {
            "framework_name": "ReConcile",
            "qid": qid,
            "question": log_data['question'],
            "options": log_data.get('options'),
            "image_path": log_data.get('image_path'),
            "ground_truth": ground_truth,
            "predicted_answer": predicted_answer,
            "is_correct": gt_str == pred_str,
            "log_content": log_data.get('case_history', {}).get('discussion_history', log_data) # 核心日志在 case_history -> discussion_history
        }
    except KeyError as e:
        print(f"Skipping log for ReConcile due to missing key: {e}")
        return None

def get_framework_parser(framework_name: str) -> Optional[Callable[[Dict[str, Any]], Optional[Dict[str, Any]]]]:
    """根据框架名称返回相应的解析器函数。"""
    parsers = {
        "ColaCare": parse_colacare_log,
        "MDAgents": parse_mdagents_log,
        "MedAgent": parse_medagent_log,  
        "ReConcile": parse_reconcile_log
    }
    return parsers.get(framework_name)


# --- 4. PROMPT ENGINEERING ---
def build_open_coding_prompts_for_colacare(case_details: Dict[str, Any], taxonomy_text: str) -> Tuple[str, Union[str, List[Dict[str, Any]]]]:
    """
    construct the prompt basing on the characteristics of different multi-agent frameworks.
    """
    system_content = (f"你是一个在医学人工智能方面的专家，精通医学知识以及医疗多智能体系统方面的知识。你现在的任务是根据医疗多智能体系统的"
                      f""  
    )
    
    # --- 框架意图描述 ---
    if case_details['framework_name'] == 'ColaCare':
        intent_description = """It simulates a multi-disciplinary medical team. Specialist 'Doctor' agents provide initial opinions. A 'Meta' agent synthesizes these opinions. Doctors then review the synthesis, leading to a consensus or further rounds of debate. The goal is to achieve a robust conclusion through expert collaboration and iterative refinement, not just simple voting."""
    elif case_details['framework_name'] == 'MDAgents':
        intent_description = """This is a dynamic, complexity-gated framework. A 'Moderator' agent first assesses the query's complexity as 'basic', 'intermediate', or 'advanced'. A 'Recruiter' then assembles the appropriate agents. For 'basic' cases, a single 'General Doctor' responds. For 'intermediate' cases, a team of specialist agents provide opinions, which are then synthesized by a 'Decision Maker'. For 'advanced' cases, multiple specialized teams (e.g., Initial Assessment, Diagnostics, Final Review) work sequentially, with the 'Decision Maker' synthesizing their final reports. The core idea is adapting the collaborative structure to the problem's difficulty."""
    elif case_details['framework_name'] == 'MedAgent':
        intent_description = """It simulates a structured consultation process. An 'Expert Gatherer' agent first identifies relevant medical specialties for the query. Then, 'Doctor' agents representing these specialties provide independent analyses. A 'Meta' (Coordinator) agent synthesizes these opinions into a single report. This report is then reviewed by the original 'Doctor' agents for agreement. Finally, a 'Decision Maker' agent produces the final answer based on the synthesis and reviews. It's a sequential process of recruitment, analysis, synthesis, review, and final decision."""
    elif case_details['framework_name'] == 'ReConcile':
        intent_description = """This framework focuses on achieving consensus through debate and confidence scoring. Multiple agents generate an initial response containing 'reasoning', an 'answer', and a numerical 'confidence' score. They then engage in multiple rounds of discussion, where they are shown the grouped answers and reasonings from the previous round. After the debate rounds, a final decision is reached via a confidence-weighted vote, where responses from more confident agents are given more weight. The core mechanism is iterative refinement through debate coupled with a quantitative confidence metric."""

    system_message = f"""
    You are a meticulous AI Collaboration Analyst specialized in auditing medical multi-agent systems. 
    
    The multi-agent framework being analyzed is **{case_details['framework_name']}**.
    Framework Intent: {intent_description}
    
    Your expertise includes analyzing collaboration patterns, identifying decision-making flaws, and classifying system behaviors according to established taxonomies.
    """

    # 2. 构建用户消息 (User Message) - 具体的案例数据
    user_text_prompt = f"""
    ### TASK ###
    Audit the collaboration log of this medical multi-agent system case. Analyze the entire decision-making process, identify key success or failure patterns, and provide a structured JSON classification.

    ### TAXONOMY (Classification System) ###
    You MUST classify the case into one or more categories from the following taxonomy. Distinguish between **Failure Modes** and **Success Patterns**.

    --- TAXONOMY START ---
    {taxonomy_text}
    --- TAXONOMY END ---

    ### ANALYSIS STEPS ###
    Perform a step-by-step analysis:

    1. **Initial Assessment:** Compare initial opinions and reasoning from the first round of interactions. Are they unanimous, complementary, or contradictory?
    2. **Interaction Dynamics Analysis:** Analyze how opinions evolve, the quality of any synthesis or debate, and how disagreements are handled. Does the process lead to convergence, or do agents talk past each other?
    3. **Final Decision Analysis:** Examine how the final decision was reached. Was it based on consensus, majority vote, a weighted mechanism, or a final arbiter? Was any critical information lost?
    4. **Classification:** Select the most prominent failure or success pattern as the `primary_classification`. List any other significant patterns in `secondary_classifications`. Provide specific evidence from the log.

    ### CASE INFORMATION ###
    - **QID**: {case_details['qid']}
    - **Question**: "{case_details['question']}"
    - **Options**: {json.dumps(case_details.get('options'), indent=2)}
    - **Ground Truth Answer**: "{case_details['ground_truth']}"
    - **Final Predicted Answer**: "{case_details['predicted_answer']}"
    - **Is Final Answer Correct?**: {case_details['is_correct']}
    """
    if case_details.get('image_path'):
        user_text_prompt += f"- **Image Provided**: Yes (see below)\n"

    user_text_prompt += f"""
    
    ### INPUT LOG ###
    Here is the complete collaboration log in JSON format. Analyze the interactions:

    ```json
    {json.dumps(case_details['log_content'], indent=2, ensure_ascii=False)}
    ```

    ### OUTPUT FORMAT ###
    First, think through the analysis steps I provided internally.
    After you have completed your analysis, your final output MUST BE a single, valid JSON object. Do not include any text, explanations, or markdown formatting before or after the JSON object. The JSON should strictly adhere to the following structure:

    ```json
    {{
    "qid": "{case_details['qid']}",
    "is_correct": {str(case_details['is_correct']).lower()},
    "primary_classification": {{
        "code": "string",
        "name": "string",
        "phase": "string"
    }},
    "secondary_classifications": [
        {{
        "code": "string",
        "name": "string",
        "phase": "string"
        }}
    ],
    "evidence": "string",
    "key_moment": "string"
    }}
    ```
    """
    # 检查是否有图片需要处理
    image_path = case_details.get("image_path")
    if image_path and os.path.exists(image_path):
        base64_image = encode_image(image_path)
        print(f"Encoded image for qid {case_details['qid']}: {image_path}")
        user_content = [
            {"type": "text", "text": user_text_prompt.strip()},
            {
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"},
            },
        ]
    else:
        if image_path:
             print(f"Warning: Image path does not exist for qid {case_details['qid']}: {image_path}")
        user_content = user_text_prompt.strip()
        
    return system_message.strip(), user_content


# --- 5. MAIN EXECUTION LOGIC ---

def process_single_log(log_path: str, output_path: str, parser: Callable, annotator: LLMAnnotator, taxonomy: str):
    """处理单个日志文件：解析、构建prompt、调用API、保存结果。"""
    # TODO taxonomy 重写为提示词
    if os.path.exists(output_path):
        return "skipped"

    log_content = load_json_file(log_path)
    if not log_content:
        return "error_loading"
    
    case_details = parser(log_content)
    print(f'framework:{case_details['framework_name']}')
    print(f'image_path:{case_details['image_path']}')
    if not case_details:
        return "error_parsing"
        
    system_message, user_message = build_annotation_prompts(case_details, taxonomy)
    
    annotation_result = annotator.annotate(system_message, user_message, case_details['qid'])
    
    if annotation_result:
        save_json(annotation_result, output_path)
        return "success"
    else:
        return "error_annotating"

def main():
    parser = argparse.ArgumentParser(
        description="Automate the annotation of multi-agent collaboration logs using a taxonomy.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("--model", required=True,type=str, help="The LLM model to use for annotation,the available models are: gpt-5.2, gemini-3-flash-preview")
    parser.add_argument("--framework", required=True,type=str, help="The multiagent framework to process.")
    parser.add_argument("--dataset", required=True,type=str, help="The dataset to process.")
    parser.add_argument("--main_llm", required=True, type=str, help="the main llm model used in multi-agent framework,like gpt-5.2,gemini-3-flash-preview")
    args = parser.parse_args()
    # --- Setup ---
    annotator = LLMAnnotator(model_key=args.model)

    framework = args.framework
    dataset = args.dataset
    main_llm = args.main_llm
    current_file_path = Path(__file__).resolve()
    project_root = current_file_path.parents[2]

    mas_collaboration_logs_path = project_root / "logs" / "mas_collaboration_results"/ "20260202" 



    # adding logs
    terminal_log_file = project_root / "logs" / f"open_coding_results" / "20260202"/ f"{framework}_{dataset}_{main_llm}_terminal.log"
    terminal_log_file.parent.mkdir(parents=True, exist_ok=True)
    print(f"!!! Terminal output is being captured to: {terminal_log_file} !!!")
    sys.stdout = DualLogger(terminal_log_file, sys.stdout)
    sys.stderr = DualLogger(terminal_log_file, sys.stderr) # 捕获报错和tqdm进度条

    output_file = project_root / "logs" / f"open_coding_results" / "20260202" / f"{framework}_{dataset}_{main_llm}.jsonl"
    error_output_file = project_root / "logs" / f"open_coding_results" / "20260202" / f"{framework}_{dataset}_{main_llm}_errors.jsonl"
    output_file.parent.mkdir(parents=True, exist_ok=True)
    error_output_file.parent.mkdir(parents=True, exist_ok=True)

    existing_qids = set()
    if output_file.exists():
        print(f"Output file {output_file} already exists. Appending new results.")
        with open(output_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line: continue
                try:
                    record = json.loads(line)
                    if "qid" in record:
                        existing_qids.add(record["qid"])
                except json.JSONDecodeError:
                    print("Warning: Found a corrupted line in jsonl file, skipping.")
        print(f"Found {len(existing_qids)} already processed cases. They will be skipped.")

    # in this file, every mas running case is one line, and each file. has 100 cases, namely 100 lines per file.
    open_coding_file = mas_collaboration_logs_path / f'{framework}_{dataset}_{main_llm}.jsonl'
    data = load_jsonl(open_coding_file)
    print(f"Total cases to process: {len(data)}")



    # --- Processing Loop ---
    print(f"\n{'='*20} Processing Framework: {framework} , dataset: {dataset}, main llm : {main_llm} {'='*20}")
    
    for item in tqdm(data, desc=f"Running open-coding on {dataset}-{framework}-{main_llm}"): 
        qid = item["qid"]

        if qid in existing_qids:
            print(f"Skipping {qid} - already processed")
            continue

        try: 
            status = process_single_log(log_path, output_path, parser_func, annotator, taxonomy_text)

            final_decision_log = full_case_history.get("final_decision_log", {})
            print("Final decision log:", final_decision_log)  # Debugging line
            final_decision_parsed = final_decision_log.get("parsed_output", {})
            print("Final decision parsed:", final_decision_parsed)  # Debugging line
            predicted_answer = final_decision_parsed.get("answer", "Error: No answer found")
            print(f"Predicted answer for {qid}: {predicted_answer}")

            item_result = {
                "qid": qid,
                "timestamp": int(time.time()),
                "question": item["question"],
                "options": item.get("options"),
                "image_path": item.get("image_path"),
                "ground_truth": item.get("answer"),
                "predicted_answer": predicted_answer,
                "case_history": full_case_history, # This now contains the full, detailed log
            }

            save_jsonl(item_result, str(output_file))
            existing_qids.add(qid)

        except Exception as e:
            print(f"Error processing item {qid}: {e}")
            # Optionally, save an error log
            error_log = {
                "qid": qid,
                "error": str(e)
            }
            save_jsonl(error_log, str(error_output_file))

if __name__ == "__main__":
    main()